### ISSUE TITLE
Wenet does not work after connecting a thermometer

### ISSUE THREAD

**Issue by GianlucaB2000** [projecthorus/wenet#11]
I connected a bme280 thermometer to the Pi zero, but Wenet now gives an error, and it doesn't work. I tried removing the thermometer, formatting the SD card, but I can't solve the problem. Suggestions ?

**Comment by GianlucaB2000** [comment]
user@raspberrypi:~/wenet/tx $ python  tx_picam_gps.py ICARO
Traceback (most recent call last):
  File "/home/user/wenet/tx/tx_picam_gps.py", line 11, in <module>
    import WenetPiCam
  File "/home/user/wenet/tx/WenetPiCam.py", line 10, in <module>
    import picamera
ModuleNotFoundError: No module named 'picamera'
user@raspberrypi:~/wenet/tx $

**Comment by GianlucaB2000** [comment]
user@raspberrypi:~/wenet/test_images $ cd ~/wenet/tx
user@raspberrypi:~/wenet/tx $ python3 init_rfm98w.py --frequency 437.500
Using deviation of 71797 Hz for Baud Rate 115200 bd.
/home/user/wenet/tx/SX127x/hardware_piloragateway.py:57: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(self.LED, GPIO.OUT)
Mode <- SLEEP
MODE=SLEEP
Frequency set to: 437.500 MHz
user@raspberrypi:~/wenet/tx $

**Comment by GianlucaB2000** [comment]
user@raspberrypi:~ $ cd ~/wenet/tx
user@raspberrypi:~/wenet/tx $ python3 init_rfm98w.py --frequency 437.500
Using deviation of 71797 Hz for Baud Rate 115200 bd.
Mode <- SLEEP
MODE=SLEEP
Frequency set to: 437.500 MHz
user@raspberrypi:~/wenet/tx $

**Comment by GianlucaB2000** [comment]
![2024-06-05 23_06_25-Greenshot](https://github.com/projecthorus/wenet/assets/108169426/8a26558a-731f-40c6-a2c4-32c2a5838257)
it is transmitting a signal, but it doesn't seem like the usual one transmitted by Wenet

**Comment by darksidelemm** [comment]
I don't know what's happened here... My guess is that when you enabled I2C it's somehow affected either the SPI communications to the radio IC, or the UART communications which drives the modulation.

I also don't have any hardware available to test this effect, sorry...
