### ISSUE TITLE
"git clone https://github.com/projecthorus/wenet.git" needs authentication

### ISSUE THREAD

**Issue by dcmk1mr2** [projecthorus/wenet#12]

**Comment by darksidelemm** [comment]
Unsure why this would be the case. 

Can you paste the full output of what happens when you run:
git clone https://github.com/projecthorus/wenet.git

**Comment by dcmk1mr2** [comment]
stinky@raspberrypi:~ $ git clone https://github.com/projecthourus/wenet.git/
Cloning into 'wenet'...
Username for 'https://github.com': dcmk1mr2@gmail.com
Password for 'https://dcmk1mr2@gmail.com@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/projecthourus/wenet.git/'

**Comment by darksidelemm** [comment]
In your example you have typo'd projecthorus.

Please try running:
git clone https://github.com/projecthorus/wenet.git

**Comment by dcmk1mr2** [comment]
I seem to have everything installed but ran into:

pi@raspberrypi:~/wenet/tx $ python3 tx_test_images.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyAMA0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/wenet/tx/tx_test_images.py", line 43, in <module>
    tx = PacketTX.PacketTX(debug=debug_output, serial_baud=args.baudrate)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/wenet/tx/PacketTX.py", line 93, in __init__
    self.s = serial.Serial(serial_port,serial_baud)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyAMA0: [Errno 2] No such file or directory: '/dev/ttyAMA0'

**Comment by darksidelemm** [comment]
The error there is pretty clear - /dev/ttyAMA0 doesn't exist. This is the serial port that wenet is trying to use to modulate the transmitter. 

Please check that you have followed the instructions, in particular the parts about enabling serial within raspi-config.

**Comment by dcmk1mr2** [comment]
Serial is enabled.  Using Raspi 0 W.

**Comment by darksidelemm** [comment]
Then I Don't know what's going on, sorry. If you have serial enabled and have also set the dtoverlay settings (See the top of the wenet TX instructions), then you should have a /dev/ttyAMA0 device.
